// <auto-generated />
namespace PanelMasterMVC5Separate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Do_not_Delete_me_please : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Do_not_Delete_me_please));
        
        string IMigrationMetadata.Id
        {
            get { return "201710260946363_Do_not_Delete_me_please"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
